version: '3.8'

services:
  stock-analyzer:
    build: .
    depends_on:
      - kafka
      - redis
      - mysql
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - MYSQL_USER=stockuser
      - MYSQL_PASSWORD=stockpass

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stock_analysis
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stockpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: